### ISSUE TITLE
Allow the assets path to be overwritten on output.

### ISSUE THREAD

**Issue by frankcarey** [devinci-code/devinci-behat-extension#5]
``` Gherkin
Feature:  Allow the assets path to be overwritten on output
  In order to quickly open dumped assets when using docker or vagrant
  As a person using the extension
  I need to be able to override the asset path that's printed to use the local path
    instead of the server path.
```
### Background

The path that assets are dumped to should be specific to the server environment and is already configurable. In the case of vagrant / docker though, the file is shared to the local machine at a different path. Since you usually want to view the html or image using local tools, you need to fix the path manually before being able to open it locally.

Here is an example:

`/var/www/test/assets/*` on the server should be reported as `~/docker/my-project/assets/*` when I set a new (optional) `asset_dump_remote_path` setting in behat.yml

**Comment by jonpugh** [comment]
I'm working on writing this variable automatically for devshop tests.

I'm not sure the config is in the right place for us to override...

What we are supposed to do now:
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Devinci\DevinciExtension\Context\DebugContext:
            asset_dump_path: %paths.base%/../assets/
        - Devinci\DevinciExtension\Context\JavascriptContext:
            maximum_wait: 30
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2:
        wd_host: http://localhost:4444/wd/hub
      browser_name: chrome
      base_url: http://localhost/
      files_path: "%paths.base%/"
      show_cmd: firefox %s
      default_session: 'goutte'
      javascript_session: 'selenium2'
    Drupal\DrupalExtension:
      api_driver: 'drupal'
```

What we'd like to do:

```

extensions:
    Devinci\DevinciExtension:
      asset_dump_path: /path/to/assets
```
